name: knote-stack

services:
  app:
    container_name: knote-app
    image: learnitguide/knotejs:1.0
    environment:
      MONGO_URL: mongodb://mongo:27017/dev
    ports:
      - "80:3000"
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    container_name: knote-mongo
    image: mongo:6
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
